### ISSUE TITLE
The application was unable to start.

### ISSUE THREAD

**Issue by maf2** [Splode/pomotroid#292]
During installation, I receive the error: "The application was unable to start correctly (0x0000005). Click OK to close the application." System: Windows 11 23H2.

**Comment by victorz** [comment]
I'm also unable to start the application on Windows. I'm the maintainer the AUR package for this application, [`pomotroid-bin`](https://aur.archlinux.org/packages/pomotroid-bin).

This is my console output:

```sh
(node:43585) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a (/opt/pomotroid/resources/app.asar/dist/electron/main.js:1:2635)
    at /opt/pomotroid/resources/app.asar/dist/electron/main.js:1:4844
(node:43585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[43585:0120/110447.479755:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
fish: Job 1, 'pomotroid' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by steph-ben** [comment]
Same issue on Linux Fedora

```
~/Downloads/pomotroid-0.13.0-linux$ ll
chrome_100_percent.pak
chrome_200_percent.pak
chrome-sandbox
icudtl.dat
libEGL.so
libffmpeg.so
libGLESv2.so
libvk_swiftshader.so
libvulkan.so
LICENSE.electron.txt
LICENSES.chromium.html
locales
pomotroid
resources
resources.pak
snapshot_blob.bin
swiftshader
v8_context_snapshot.bin
vk_swiftshader_icd.json

~/Downloads/pomotroid-0.13.0-linux$ ./pomotroid 
[24247:0214/121311.242921:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trappe pour point d'arrêt et de trace (core dumped)

```

**Comment by p-a-s-c-a-l** [comment]
![Image](https://github.com/user-attachments/assets/b1016f4f-96fa-4c59-8cef-7de28b77a391)

**Comment by enrico3** [comment]
In Linux Mint 21.3 i also get the error 
`GPU process isn't usable. Goodbye.`

**Comment by victorz** [comment]
Safe to say by now that this is abandonware. I think I'll orphan the AUR package since this won't be fixed.

**Comment by moatmai** [comment]
> Safe to say by now that this is abandonware. I think I'll orphan the AUR package since this won't be fixed.

The app has been updated. Does the problem still appear in the current version (1.2.0+85d3710.dirty)?

**Comment by victorz** [comment]
I don't plan to test this as I've lost interest since the app was broken for years, combined with the silence from the developer. It probably works? 🤷‍♂️ Good luck to anyone who is interested in this software going forward! Unsubscribing.

**Comment by Splode** [comment]
Closing as stale.
